version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  lint-code:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install Linters
          command: pip install black flake8
      - run:
          name: black
          command: black --line-length 79 --check .
      - run:
          name: flake8
          command: flake8 --ignore E203,W503 .

  test-code:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install requirements from subdirs
          command: |
            pip install -r data_building/requirements.txt
            pip install -r evaluation/requirements.txt
      - run:
          name: Run unittests
          command: python -m unittest discover tests/

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint-code
      - test-code
